package com.chaseschwartz.extractcraft.items;

import java.util.List;

public record LooseLootDefinition(String id, String displayName, String category, String rarity, int tier, String description, double weight, int gridWidth, int gridHeight, int value) {
    public static final List<LooseLootDefinition> DEFINITIONS = List.of(
            new LooseLootDefinition("sealed_cable_bundle", "Sealed Cable Bundle", "electronics", "blue", 2, "A sealed bundle of military-grade cable used in field repairs.", 0.6D, 1, 1, 420),
            new LooseLootDefinition("field_radio_battery", "Field Radio Battery", "electronics", "blue", 2, "A rugged battery pulled from a field radio pack.", 0.9D, 1, 1, 560),
            new LooseLootDefinition("cracked_rangefinder_lens", "Cracked Rangefinder Lens", "optics", "blue", 2, "A damaged optic lens still useful for calibration parts.", 0.4D, 1, 1, 680),
            new LooseLootDefinition("spent_data_tape", "Spent Data Tape", "intel", "blue", 2, "Old magnetic tape with fragments of overwritten patrol logs.", 0.2D, 1, 1, 360),
            new LooseLootDefinition("maintenance_key_fob", "Maintenance Key Fob", "access", "blue", 2, "A worn access fob for maintenance corridors and service doors.", 0.1D, 1, 1, 620),
            new LooseLootDefinition("rusted_dog_tags", "Rusted Dog Tags", "trophy", "blue", 2, "Corroded identification tags from an unknown combatant.", 0.1D, 1, 1, 310),
            new LooseLootDefinition("combat_tourniquet_pack", "Combat Tourniquet Pack", "field_medical", "blue", 2, "A sealed pack of emergency tourniquets for field trauma.", 0.3D, 1, 1, 480),
            new LooseLootDefinition("sterile_gauze_brick", "Sterile Gauze Brick", "home_medical", "blue", 2, "Compressed sterile gauze wrapped for rapid medical restock.", 0.4D, 1, 1, 390),
            new LooseLootDefinition("antibiotic_strip", "Antibiotic Strip", "home_medical", "blue", 2, "A sealed strip of antibiotics prized by field medics.", 0.1D, 1, 1, 580),
            new LooseLootDefinition("water_purifier_cartridge", "Water Purifier Cartridge", "survival_utility", "blue", 2, "A filter cartridge for portable purifier systems.", 0.4D, 1, 1, 540),
            new LooseLootDefinition("mre_flavor_pack", "MRE Flavor Pack", "survival_utility", "blue", 2, "A morale-saving packet of ration flavoring and salts.", 0.1D, 1, 1, 260),
            new LooseLootDefinition("sealed_coffee_tin", "Sealed Coffee Tin", "survival_utility", "blue", 2, "A sealed metal coffee tin from a kitchen or break-room shelf.", 0.5D, 1, 1, 620),
            new LooseLootDefinition("instant_noodle_cup", "Instant Noodle Cup", "survival_utility", "blue", 2, "A cup of instant noodles with the lid still sealed.", 0.2D, 1, 1, 260),
            new LooseLootDefinition("vacuum_tea_brick", "Vacuum Tea Brick", "survival_utility", "blue", 2, "A vacuum-wrapped compressed tea brick prized by civilian traders.", 0.3D, 1, 1, 540),
            new LooseLootDefinition("canned_peaches", "Canned Peaches", "survival_utility", "blue", 2, "A labeled can of peaches with the pull tab intact.", 0.6D, 1, 1, 340),
            new LooseLootDefinition("chocolate_bar_pack", "Chocolate Bar Pack", "survival_utility", "blue", 2, "A wrapped chocolate bar pack still good for morale.", 0.1D, 1, 1, 310),
            new LooseLootDefinition("storm_lighter", "Storm Lighter", "survival_utility", "blue", 2, "A rugged windproof lighter built for bad weather and field use.", 0.2D, 1, 1, 780),
            new LooseLootDefinition("signal_mirror", "Signal Mirror", "survival_utility", "blue", 2, "A small reflective signal mirror with a sighting hole.", 0.1D, 1, 1, 620),
            new LooseLootDefinition("emergency_blanket_roll", "Emergency Blanket Roll", "survival_utility", "blue", 2, "A shiny foil emergency blanket rolled tight with a strap.", 0.3D, 1, 1, 520),
            new LooseLootDefinition("water_purification_tabs", "Water Purification Tabs", "survival_utility", "blue", 2, "A sealed strip of tablets for making questionable water drinkable.", 0.1D, 1, 1, 690),
            new LooseLootDefinition("spark_plug_set", "Spark Plug Set", "industrial_tools", "blue", 2, "A matched set of plugs scavenged from motor pool stock.", 0.5D, 1, 1, 610),
            new LooseLootDefinition("pressure_gauge", "Pressure Gauge", "industrial_tools", "blue", 2, "A round dial gauge pulled from a boiler or utility line.", 0.5D, 1, 1, 760),
            new LooseLootDefinition("valve_wheel", "Valve Wheel", "industrial_tools", "blue", 2, "A red metal valve wheel from an old pipe control station.", 1.2D, 1, 2, 720),
            new LooseLootDefinition("welding_nozzle", "Welding Nozzle", "industrial_tools", "blue", 2, "A worn torch nozzle with enough clean brass to reuse.", 0.4D, 1, 1, 540),
            new LooseLootDefinition("bearing_set", "Bearing Set", "industrial_tools", "blue", 2, "A clustered set of machine bearings packed in shop grease.", 0.7D, 1, 1, 690),
            new LooseLootDefinition("drill_chuck", "Drill Chuck", "industrial_tools", "blue", 2, "A chunky drill chuck salvaged from a workshop toolhead.", 0.8D, 1, 1, 820),
            new LooseLootDefinition("braided_hose_bundle", "Braided Hose Bundle", "industrial_tools", "blue", 2, "A coiled reinforced hose bundle from a vehicle bay.", 0.9D, 1, 2, 1180),
            new LooseLootDefinition("worn_tool_roll", "Worn Tool Roll", "industrial_tools", "blue", 2, "A canvas roll containing battered but usable field tools.", 1.0D, 1, 2, 750),
            new LooseLootDefinition("duct_tape_stack", "Duct Tape Stack", "industrial_tools", "blue", 2, "Multiple tape rolls flattened for pack storage.", 0.3D, 1, 1, 300),
            new LooseLootDefinition("brass_screw_tin", "Brass Screw Tin", "industrial_tools", "blue", 2, "A rattling tin of small brass fasteners.", 0.4D, 1, 1, 290),
            new LooseLootDefinition("ceramic_fuse", "Ceramic Fuse", "electronics", "blue", 2, "A heat-resistant fuse for older industrial circuits.", 0.2D, 1, 1, 370),
            new LooseLootDefinition("signal_flare_tube", "Signal Flare Tube", "survival_utility", "blue", 2, "A sealed flare tube used to mark extraction or distress points.", 0.6D, 1, 2, 690),
            new LooseLootDefinition("flare_case", "Flare Case", "survival_utility", "blue", 2, "A red emergency flare case sealed for rough field storage.", 0.6D, 1, 2, 980),
            new LooseLootDefinition("filter_straw", "Filter Straw", "survival_utility", "blue", 2, "A slim survival filter straw for emergency water collection.", 0.2D, 1, 2, 860),
            new LooseLootDefinition("training_ammo_voucher", "Training Ammo Voucher", "intel", "blue", 2, "A stamped voucher redeemable at a restricted training armory.", 0.1D, 1, 1, 450),
            new LooseLootDefinition("laminated_zone_map", "Laminated Zone Map", "intel", "blue", 2, "A weatherproof map marked with old patrol routes.", 0.2D, 1, 1, 820),
            new LooseLootDefinition("oily_cleaning_cloth", "Oily Cleaning Cloth", "tools", "blue", 2, "A treated cloth used for weapon and tool maintenance.", 0.1D, 1, 1, 250),
            new LooseLootDefinition("pocket_multimeter", "Pocket Multimeter", "electronics", "blue", 2, "A compact meter for diagnosing circuits under fire.", 0.4D, 1, 1, 900),
            new LooseLootDefinition("damaged_keypad_panel", "Damaged Keypad Panel", "security", "blue", 2, "A battered keypad panel from a locked facility door.", 0.7D, 1, 2, 880),
            new LooseLootDefinition("field_notebook", "Field Notebook", "intel", "blue", 2, "A pocket notebook filled with partial grid references.", 0.2D, 1, 1, 470),
            new LooseLootDefinition("ration_coupon_stack", "Ration Coupon Stack", "survival_utility", "blue", 2, "A bundle of ration coupons still recognized by some traders.", 0.1D, 1, 1, 280),
            new LooseLootDefinition("plastic_med_vials", "Plastic Med Vials", "field_medical", "blue", 2, "Clean plastic vials useful for field sample storage.", 0.2D, 1, 1, 520),
            new LooseLootDefinition("pill_bottle_rx", "Pill Bottle RX", "home_medical", "blue", 2, "An orange prescription bottle with the label mostly intact.", 0.2D, 1, 1, 640),
            new LooseLootDefinition("blister_painkillers", "Blister Painkillers", "home_medical", "blue", 2, "A foil blister strip of common painkiller tablets.", 0.1D, 1, 1, 420),
            new LooseLootDefinition("first_aid_ointment", "First Aid Ointment", "home_medical", "blue", 2, "A small ointment tube from a civilian first aid kit.", 0.1D, 1, 1, 360),
            new LooseLootDefinition("glass_cough_syrup", "Glass Cough Syrup", "home_medical", "blue", 2, "A brown glass cough syrup bottle with a stained pharmacy label.", 0.4D, 1, 1, 520),
            new LooseLootDefinition("adhesive_bandage_box", "Adhesive Bandage Box", "home_medical", "blue", 2, "A small box of adhesive bandages from a medicine cabinet.", 0.2D, 1, 1, 390),
            new LooseLootDefinition("digital_thermometer", "Digital Thermometer", "home_medical", "blue", 2, "A slim digital thermometer with a tiny cracked display.", 0.1D, 1, 2, 560),
            new LooseLootDefinition("inhaler_blue", "Blue Inhaler", "home_medical", "blue", 2, "A blue rescue inhaler with a few doses left inside.", 0.2D, 1, 1, 740),
            new LooseLootDefinition("saline_eye_drops", "Saline Eye Drops", "home_medical", "blue", 2, "A small plastic dropper bottle of sterile saline eye drops.", 0.1D, 1, 1, 310),
            new LooseLootDefinition("specimen_slide_case", "Specimen Slide Case", "lab_bio", "blue", 2, "A flat case holding labeled microscope specimen slides.", 0.2D, 1, 1, 740),
            new LooseLootDefinition("microscope_lens", "Microscope Lens", "optics", "blue", 2, "A compact brass and black optical lens assembly from a lab scope.", 0.2D, 1, 1, 890),
            new LooseLootDefinition("petri_dish_stack", "Petri Dish Stack", "lab_bio", "blue", 2, "A stack of clear petri dishes with sealed colored samples.", 0.3D, 1, 1, 680),
            new LooseLootDefinition("hydraulic_valve", "Hydraulic Valve", "industrial_tools", "blue", 2, "A heavy valve from a vehicle or loading system.", 1.1D, 1, 2, 980),
            new LooseLootDefinition("copper_wire_spool", "Copper Wire Spool", "electronics", "blue", 2, "A compact spool of insulated copper wire.", 0.6D, 1, 1, 640),
            new LooseLootDefinition("cracked_phone_screen", "Cracked Phone Screen", "electronics", "blue", 2, "A cracked display panel with recoverable touch layers.", 0.1D, 1, 1, 410),
            new LooseLootDefinition("folded_evacuate_notice", "Folded Evacuation Notice", "intel", "blue", 2, "An evacuation notice with handwritten route changes.", 0.1D, 1, 1, 270),
            new LooseLootDefinition("security_badge_blank", "Security Badge Blank", "access", "blue", 2, "A blank badge ready for encoding or forgery.", 0.1D, 1, 1, 580),
            new LooseLootDefinition("office_stamp_kit", "Office Stamp Kit", "office_admin", "blue", 2, "A rubber stamp and ink pad from an administrative desk.", 0.4D, 1, 1, 620),
            new LooseLootDefinition("security_badge_stack", "Security Badge Stack", "office_admin", "blue", 2, "A small stack of blank and expired security badges.", 0.2D, 1, 1, 780),
            new LooseLootDefinition("brass_nameplate", "Brass Nameplate", "civilian_valuable", "blue", 2, "A polished brass desk nameplate from an executive office.", 0.6D, 1, 1, 950),
            new LooseLootDefinition("travel_mug", "Travel Mug", "food_comfort", "blue", 2, "An insulated travel mug with a dented but intact lid.", 0.4D, 1, 1, 520),
            new LooseLootDefinition("sealed_spice_jar", "Sealed Spice Jar", "survival_utility", "blue", 2, "A small sealed spice jar with bright preserved contents.", 0.2D, 1, 1, 480),
            new LooseLootDefinition("shredded_document_bag", "Shredded Document Bag", "office_admin", "blue", 2, "A clear evidence bag packed with shredded document strips.", 0.3D, 1, 2, 860),
            new LooseLootDefinition("low_grade_lubricant", "Low-Grade Lubricant", "industrial_tools", "blue", 2, "A cheap lubricant tube useful for locks and worn machinery.", 0.4D, 1, 1, 390),
            new LooseLootDefinition("gold_wristwatch", "Gold Wristwatch", "luxury_collectible", "blue", 2, "A scuffed but valuable gold wristwatch from a private residence.", 0.2D, 1, 1, 1350),
            new LooseLootDefinition("silver_locket", "Silver Locket", "luxury_collectible", "blue", 2, "A tarnished silver locket with a worn clasp and personal engraving.", 0.1D, 1, 1, 820),
            new LooseLootDefinition("antique_compass", "Antique Compass", "intel", "blue", 2, "A brass compass with old route marks scratched into the case.", 0.3D, 1, 1, 1150),
            new LooseLootDefinition("camera_lens", "Camera Lens", "optics", "blue", 2, "A compact camera lens with salvageable coated glass.", 0.4D, 1, 1, 1200),
            new LooseLootDefinition("engraved_lighter", "Engraved Lighter", "civilian_valuable", "blue", 2, "A battered lighter with a name and unit number engraved on the side.", 0.2D, 1, 1, 420),
            new LooseLootDefinition("perfume_bottle", "Perfume Bottle", "luxury_collectible", "blue", 2, "A small luxury perfume bottle that survived the evacuation intact.", 0.4D, 1, 1, 980),
            new LooseLootDefinition("fountain_pen_case", "Fountain Pen Case", "office_admin", "blue", 2, "A slim case holding a fountain pen favored for signed orders.", 0.2D, 1, 1, 1050),
            new LooseLootDefinition("encrypted_usb_token", "Encrypted USB Token", "electronics", "purple", 3, "A locked token containing encrypted facility credentials.", 0.1D, 1, 1, 2200),
            new LooseLootDefinition("drone_flight_controller", "Drone Flight Controller", "electronics", "purple", 3, "A compact controller board for small reconnaissance drones.", 0.5D, 1, 1, 3600),
            new LooseLootDefinition("thermal_lens_module", "Thermal Lens Module", "optics", "purple", 3, "A sensitive lens module used in thermal imaging devices.", 0.4D, 1, 1, 5100),
            new LooseLootDefinition("ballistic_fiber_roll", "Ballistic Fiber Roll", "armor_materials", "purple", 3, "A roll of woven ballistic fiber for armor repair.", 1.1D, 1, 2, 2800),
            new LooseLootDefinition("ceramic_plate_insert", "Ceramic Plate Insert", "armor_materials", "purple", 3, "A dense ceramic insert cut for plate carrier systems.", 2.3D, 2, 2, 4100),
            new LooseLootDefinition("kevlar_stitch_kit", "Kevlar Stitch Kit", "armor_materials", "purple", 3, "A reinforced stitching kit for torn combat textiles.", 0.7D, 1, 1, 2500),
            new LooseLootDefinition("tactical_tablet", "Tactical Tablet", "electronics", "purple", 3, "A hardened tablet with cracked but readable tactical overlays.", 0.8D, 2, 2, 6200),
            new LooseLootDefinition("satellite_phone", "Satellite Phone", "electronics", "purple", 3, "A satellite handset with a restricted network profile.", 0.7D, 1, 2, 5400),
            new LooseLootDefinition("secure_radio_module", "Secure Radio Module", "electronics", "purple", 3, "An encrypted module used in secure squad radios.", 0.6D, 1, 1, 4300),
            new LooseLootDefinition("biometric_scanner", "Biometric Scanner", "security", "purple", 3, "A palm scanner pulled from a checkpoint access post.", 0.5D, 1, 1, 4900),
            new LooseLootDefinition("lab_sample_cooler", "Lab Sample Cooler", "lab_bio", "purple", 3, "An insulated cooler for transporting volatile medical samples.", 1.8D, 2, 2, 5700),
            new LooseLootDefinition("reagent_ampoule_rack", "Reagent Ampoule Rack", "lab_bio", "purple", 3, "A tiny rack of colored reagent ampoules from a secure lab bench.", 0.5D, 1, 1, 3400),
            new LooseLootDefinition("biohazard_sample_tube", "Biohazard Sample Tube", "lab_bio", "purple", 3, "A sealed sample tube marked with a bright biohazard warning.", 0.3D, 1, 1, 4600),
            new LooseLootDefinition("centrifuge_rotor", "Centrifuge Rotor", "lab_bio", "purple", 3, "A round metal centrifuge rotor with precision-drilled sample wells.", 1.2D, 2, 2, 5200),
            new LooseLootDefinition("sealed_lab_notebook", "Sealed Lab Notebook", "intel", "purple", 3, "A strapped lab notebook sealed with a warning label.", 0.4D, 1, 1, 4100),
            new LooseLootDefinition("calibration_weight_set", "Calibration Weight Set", "industrial_tools", "purple", 3, "A small tray of polished calibration weights for lab instruments.", 1.0D, 1, 2, 3800),
            new LooseLootDefinition("surgical_stapler_kit", "Surgical Stapler Kit", "field_medical", "purple", 3, "A sealed kit for fast wound closure in the field.", 0.5D, 1, 1, 2900),
            new LooseLootDefinition("hemostatic_injector_pack", "Hemostatic Injector Pack", "field_medical", "purple", 3, "A pack of injector cartridges for severe bleeding control.", 0.4D, 1, 1, 3200),
            new LooseLootDefinition("blacksite_access_badge", "Blacksite Access Badge", "access", "purple", 3, "A restricted badge tied to blacksite facility access.", 0.1D, 1, 1, 6500),
            new LooseLootDefinition("armory_maintenance_card", "Armory Maintenance Card", "access", "purple", 3, "A maintenance card for secured armory service panels.", 0.1D, 1, 1, 3700),
            new LooseLootDefinition("executive_keyring", "Executive Keyring", "office_admin", "purple", 3, "A ring of executive keys with one polished master key.", 0.2D, 1, 1, 4200),
            new LooseLootDefinition("sealed_cash_envelope", "Sealed Cash Envelope", "office_admin", "purple", 3, "A sealed cash envelope thick enough to show the banded bills inside.", 0.2D, 1, 1, 5600),
            new LooseLootDefinition("cigarette_carton", "Cigarette Carton", "contraband", "purple", 3, "A sealed carton of cigarettes with intact tax markings.", 0.4D, 1, 2, 3200),
            new LooseLootDefinition("locked_file_tube", "Locked File Tube", "office_admin", "purple", 3, "A cylindrical document tube capped with a small lock.", 0.7D, 1, 2, 3900),
            new LooseLootDefinition("encrypted_access_fob", "Encrypted Access Fob", "security", "purple", 3, "A modern encrypted access token issued for secured offices.", 0.1D, 1, 1, 6200),
            new LooseLootDefinition("diamond_earrings_case", "Diamond Earrings Case", "luxury_collectible", "purple", 3, "A velvet jewelry case holding a pair of small diamond earrings.", 0.2D, 1, 1, 5200),
            new LooseLootDefinition("sealed_diplomatic_medal", "Sealed Diplomatic Medal", "luxury_collectible", "purple", 3, "A diplomatic medal sealed in a scratched display case.", 0.3D, 1, 1, 6800),
            new LooseLootDefinition("ceremonial_dagger_hilt", "Ceremonial Dagger Hilt", "luxury_collectible", "purple", 3, "A jeweled ceremonial dagger hilt recovered without its blade.", 0.5D, 1, 2, 6400),
            new LooseLootDefinition("antique_music_box", "Antique Music Box", "pawn_collectible", "purple", 3, "An ornate wind-up music box from a civilian luxury collection.", 0.9D, 2, 2, 7200),
            new LooseLootDefinition("designer_wallet", "Designer Wallet", "pawn_collectible", "purple", 3, "A folded designer wallet with cash and a premium card still tucked inside.", 0.2D, 1, 1, 4200),
            new LooseLootDefinition("luxury_sunglasses", "Luxury Sunglasses", "luxury_collectible", "purple", 3, "Folded dark sunglasses with a polished gold frame.", 0.2D, 1, 1, 4200),
            new LooseLootDefinition("silver_cigarette_case", "Silver Cigarette Case", "pawn_collectible", "purple", 3, "An engraved silver flip case from an old lounge collection.", 0.4D, 1, 2, 4700),
            new LooseLootDefinition("velvet_jewelry_pouch", "Velvet Jewelry Pouch", "luxury_collectible", "purple", 3, "A soft velvet drawstring pouch with a glint of jewelry inside.", 0.2D, 1, 1, 5200),
            new LooseLootDefinition("crystal_decanter", "Crystal Decanter", "luxury_collectible", "purple", 3, "An elegant crystal decanter with the stopper still intact.", 1.0D, 1, 2, 6200),
            new LooseLootDefinition("antique_hand_mirror", "Antique Hand Mirror", "luxury_collectible", "purple", 3, "An ornate handheld mirror from a luxury vanity set.", 0.5D, 1, 2, 4800),
            new LooseLootDefinition("gold_cufflinks", "Gold Cufflinks", "luxury_collectible", "purple", 3, "A matched pair of gold cufflinks kept in a small executive case.", 0.1D, 1, 1, 5900),
            new LooseLootDefinition("silver_compact_case", "Silver Compact Case", "luxury_collectible", "purple", 3, "An engraved silver compact case with a polished clasp.", 0.2D, 1, 1, 4700),
            new LooseLootDefinition("pocket_cigar_case", "Pocket Cigar Case", "pawn_collectible", "purple", 3, "A slim pocket cigar case with a worn luxury finish.", 0.3D, 1, 2, 4200),
            new LooseLootDefinition("gemstone_tie_pin", "Gemstone Tie Pin", "luxury_collectible", "gold", 4, "A delicate tie pin set with a bright cut gemstone.", 0.1D, 1, 1, 15500),
            new LooseLootDefinition("ivory_letter_opener", "Ivory Letter Opener", "pawn_collectible", "purple", 3, "A decorative letter opener with an ivory-style handle.", 0.3D, 1, 2, 5400),
            new LooseLootDefinition("velvet_ring_box", "Velvet Ring Box", "luxury_collectible", "gold", 4, "A small velvet ring box left open with the ring still inside.", 0.2D, 1, 1, 22500),
            new LooseLootDefinition("vintage_camera", "Vintage Camera", "pawn_collectible", "purple", 3, "An old rangefinder camera with a scratched but intact body.", 0.8D, 1, 2, 5800),
            new LooseLootDefinition("silver_pocket_flask", "Silver Pocket Flask", "pawn_collectible", "purple", 3, "An engraved silver flask from a private bar cabinet.", 0.4D, 1, 1, 4300),
            new LooseLootDefinition("rare_stamp_album", "Rare Stamp Album", "pawn_collectible", "gold", 4, "A small album of rare stamps from a collector's safe.", 0.3D, 1, 1, 17200),
            new LooseLootDefinition("antique_porcelain_figurine", "Antique Porcelain Figurine", "pawn_collectible", "purple", 3, "A fragile porcelain figurine with blue hand-painted detail.", 0.6D, 1, 2, 6900),
            new LooseLootDefinition("gold_fountain_pen", "Gold Fountain Pen", "pawn_collectible", "gold", 4, "A fancy gold fountain pen with a clean nib and heavy cap.", 0.2D, 1, 1, 16500),
            new LooseLootDefinition("collector_card_slab", "Collector Card Slab", "pawn_collectible", "gold", 4, "A graded collector card sealed in a clear protective slab.", 0.2D, 1, 1, 19600),
            new LooseLootDefinition("silver_pocket_knife", "Silver Pocket Knife", "pawn_collectible", "purple", 3, "A folded ornate pocket knife with polished silver scales.", 0.3D, 1, 1, 5200),
            new LooseLootDefinition("antique_music_cylinder", "Antique Music Cylinder", "pawn_collectible", "purple", 3, "A brass music cylinder from an old mechanical music box.", 0.4D, 1, 1, 4700),
            new LooseLootDefinition("redacted_patrol_orders", "Redacted Patrol Orders", "intel", "purple", 3, "Orders with heavy redactions and a few useful route timings.", 0.1D, 1, 1, 4500),
            new LooseLootDefinition("sealed_evidence_pouch", "Sealed Evidence Pouch", "intel", "purple", 3, "A tamper-marked pouch containing chain-of-custody fragments.", 0.2D, 1, 1, 3400),
            new LooseLootDefinition("military_crypto_ledger", "Military Crypto Ledger", "intel", "purple", 3, "A paper ledger of rotating military crypto references.", 0.3D, 1, 1, 7100),
            new LooseLootDefinition("hardened_drive_caddy", "Hardened Drive Caddy", "electronics", "purple", 3, "A shockproof drive carrier from a command workstation.", 0.6D, 1, 1, 3900),
            new LooseLootDefinition("optic_calibration_tool", "Optic Calibration Tool", "optics", "purple", 3, "A precise tool for aligning advanced sight modules.", 0.4D, 1, 1, 3000),
            new LooseLootDefinition("compact_signal_jammer", "Compact Signal Jammer", "security", "purple", 3, "A compact jammer used to blind short-range sensors.", 0.9D, 1, 2, 6900),
            new LooseLootDefinition("reinforced_cable_harness", "Reinforced Cable Harness", "industrial_tools", "purple", 3, "A rugged harness from a military generator bay.", 1.4D, 1, 2, 3100),
            new LooseLootDefinition("compact_camp_stove", "Compact Camp Stove", "industrial_tools", "purple", 3, "A tiny fold-out stove burner packed for survival kits.", 0.8D, 1, 2, 2400),
            new LooseLootDefinition("firestarter_tin", "Firestarter Tin", "survival_utility", "purple", 3, "An open metal tin packed with matches, flint, and dry tinder.", 0.4D, 1, 1, 2600),
            new LooseLootDefinition("fuse_box_module", "Fuse Box Module", "industrial_tools", "purple", 3, "A compact fuse block stripped from a maintenance panel.", 0.8D, 1, 2, 2400),
            new LooseLootDefinition("pump_impeller", "Pump Impeller", "industrial_tools", "purple", 3, "A machined impeller rotor from an industrial pump assembly.", 1.6D, 2, 2, 3200),
            new LooseLootDefinition("restricted_medical_manifest", "Restricted Medical Manifest", "intel", "purple", 3, "A manifest listing controlled medical shipments and routing.", 0.1D, 1, 1, 5200),
            new LooseLootDefinition("quantum_signal_chip", "Quantum Signal Chip", "electronics", "gold", 4, "A rare signal chip built for hardened encrypted relays.", 0.1D, 1, 1, 14500),
            new LooseLootDefinition("classified_ssd_array", "Classified SSD Array", "electronics", "gold", 4, "A compact SSD array marked for classified systems only.", 0.5D, 1, 1, 18200),
            new LooseLootDefinition("advanced_nvg_assembly", "Advanced NVG Assembly", "optics", "gold", 4, "A complete night vision assembly with intact tubes.", 0.8D, 2, 2, 17500),
            new LooseLootDefinition("smart_ballistic_plate", "Smart Ballistic Plate", "armor_materials", "gold", 4, "A smart plate with embedded impact telemetry layers.", 3.0D, 2, 2, 19500),
            new LooseLootDefinition("reactive_armor_tile", "Reactive Armor Tile", "armor_materials", "gold", 4, "A sealed reactive tile from an experimental armor kit.", 3.6D, 2, 2, 22500),
            new LooseLootDefinition("exo_fiber_harness", "Exo-Fiber Harness", "armor_materials", "gold", 4, "A woven harness designed to anchor powered exo components.", 2.2D, 2, 3, 27800),
            new LooseLootDefinition("precision_gyro_stabilizer", "Precision Gyro Stabilizer", "weapon_parts", "gold", 4, "A stabilizer module used in precision weapon platforms.", 0.7D, 1, 1, 15000),
            new LooseLootDefinition("adaptive_suppressor_core", "Adaptive Suppressor Core", "weapon_parts", "gold", 4, "A suppressor core with adjustable gas-flow chambers.", 0.8D, 1, 2, 15600),
            new LooseLootDefinition("secure_ops_laptop", "Secure Ops Laptop", "electronics", "gold", 4, "A hardened operations laptop with secure boot hardware.", 2.4D, 2, 2, 33500),
            new LooseLootDefinition("commanders_encrypted_drive", "Commander's Encrypted Drive", "intel", "gold", 4, "A restricted drive containing encrypted command data.", 0.2D, 1, 1, 26000),
            new LooseLootDefinition("black_budget_payroll", "Black Budget Payroll", "intel", "gold", 4, "A payroll ledger tied to off-books battlefield contractors.", 0.2D, 1, 1, 31000),
            new LooseLootDefinition("diplomatic_courier_pouch", "Diplomatic Courier Pouch", "contraband", "gold", 4, "A sealed courier pouch with diplomatic chain markings.", 0.7D, 1, 2, 29500),
            new LooseLootDefinition("lab_grade_stimulant_case", "Lab-Grade Stimulant Case", "rare_medical", "gold", 4, "A locked case of high-grade stimulant compounds.", 1.2D, 2, 2, 16800),
            new LooseLootDefinition("portable_blood_analyzer", "Portable Blood Analyzer", "rare_medical", "gold", 4, "A portable analyzer used by trauma teams and field labs.", 0.9D, 1, 2, 15000),
            new LooseLootDefinition("nano_suture_cartridge", "Nano-Suture Cartridge", "rare_medical", "gold", 4, "A tiny cartridge of experimental wound-closure filament.", 0.2D, 1, 1, 12500),
            new LooseLootDefinition("gold_chess_king", "Gold Chess King", "luxury_collectible", "gold", 4, "A solid gold chess king taken from an executive collection.", 0.8D, 1, 1, 22000),
            new LooseLootDefinition("antique_pocket_watch", "Antique Pocket Watch", "luxury_collectible", "gold", 4, "An open antique pocket watch with a delicate chain and intact face.", 0.2D, 1, 1, 18500),
            new LooseLootDefinition("pearl_bracelet", "Pearl Bracelet", "luxury_collectible", "gold", 4, "A loop of matched pearls with a tiny gold clasp.", 0.1D, 1, 1, 16000),
            new LooseLootDefinition("rare_coin_case", "Rare Coin Case", "pawn_collectible", "gold", 4, "A small display case holding rare gold and silver collector coins.", 0.4D, 1, 1, 21000),
            new LooseLootDefinition("jeweled_brooch", "Jeweled Brooch", "luxury_collectible", "gold", 4, "An ornate brooch set with bright stones and delicate metalwork.", 0.1D, 1, 1, 24000),
            new LooseLootDefinition("platinum_data_wafer", "Platinum Data Wafer", "electronics", "gold", 4, "A thin platinum data wafer used for high-security archival storage.", 0.1D, 1, 1, 32000),
            new LooseLootDefinition("royal_signet_ring", "Royal Signet Ring", "luxury_collectible", "gold", 4, "A heavy gold signet ring set with a sealed royal crest.", 0.1D, 1, 1, 34000),
            new LooseLootDefinition("heart_of_the_dam", "Heart of the Dam", "jackpot", "red", 5, "A legendary industrial core pulled from the dam control complex.", 4.5D, 3, 3, 105000),
            new LooseLootDefinition("gemstone_reliquary", "Gemstone Reliquary", "jackpot", "red", 5, "An ornate reliquary packed with rare cut gemstones.", 2.4D, 2, 2, 145000),
            new LooseLootDefinition("luxury_gold_bar", "Luxury Gold Bar", "jackpot", "red", 5, "A stamped luxury bullion bar from a private reserve.", 1.8D, 1, 2, 90000),
            new LooseLootDefinition("blacksite_master_ledger", "Blacksite Master Ledger", "intel", "red", 5, "A master ledger linking blacksite operations, accounts, and handlers.", 0.7D, 2, 2, 95000),
            new LooseLootDefinition("prototype_exo_core", "Prototype Exo-Core", "armor_materials", "red", 5, "A rare powered exo core with intact control architecture.", 5.0D, 2, 3, 112000),
            new LooseLootDefinition("gold_tactical_pack_frame", "Gold Tactical Pack Frame", "armor_materials", "red", 5, "A gold-anodized frame from an elite tactical pack prototype.", 3.4D, 2, 3, 75000),
            new LooseLootDefinition("command_ai_processor", "Command AI Processor", "electronics", "red", 5, "A rare command processor pulled from a hardened battlefield AI unit.", 1.3D, 2, 2, 148000),
            new LooseLootDefinition("satellite_uplink_beacon", "Satellite Uplink Beacon", "security", "red", 5, "A military uplink beacon capable of reaching restricted satellites.", 2.1D, 2, 2, 91000),
            new LooseLootDefinition("classified_warhead_circuit", "Classified Warhead Circuit", "contraband", "red", 5, "A classified firing circuit from a banned warhead program.", 0.9D, 1, 2, 125000),
            new LooseLootDefinition("sealed_blacksite_relic", "Sealed Blacksite Relic", "jackpot", "red", 5, "A sealed artifact container recovered from a hidden blacksite room.", 1.4D, 2, 2, 98000),
            new LooseLootDefinition("glowing_core_fragment", "Glowing Core Fragment", "power", "red", 5, "A cracked glowing fragment locked inside a scorched metal clamp.", 0.9D, 1, 2, 118000),
            new LooseLootDefinition("unknown_specimen_jar", "Unknown Specimen Jar", "lab_bio", "gold", 4, "A sealed lab jar holding an unidentified organic specimen.", 0.8D, 1, 2, 28500),
            new LooseLootDefinition("encrypted_prayer_tablet", "Encrypted Prayer Tablet", "intel", "red", 5, "An old-world tablet etched with glowing encrypted symbols.", 1.8D, 2, 2, 132000),
            new LooseLootDefinition("anomalous_compass", "Anomalous Compass", "intel", "gold", 4, "A warped compass whose glowing needle refuses to point north.", 0.4D, 1, 1, 24500),
            new LooseLootDefinition("redacted_photo_locket", "Redacted Photo Locket", "weird_lore", "purple", 3, "An open locket with a blacked-out portrait sealed under cracked glass.", 0.1D, 1, 1, 6400),
            new LooseLootDefinition("sealed_eye_capsule", "Sealed Eye Capsule", "lab_bio", "gold", 4, "A medical capsule containing an eye-like sensor suspended in fluid.", 0.3D, 1, 1, 31800),
            new LooseLootDefinition("ancient_access_coin", "Ancient Access Coin", "access", "gold", 4, "A coin-key hybrid engraved with old circuitry and worn access runes.", 0.2D, 1, 1, 27600),
            new LooseLootDefinition("omega_protocol_drive", "Omega Protocol Drive", "intel", "red", 5, "A restricted drive carrying fragments of Omega Protocol orders.", 0.2D, 1, 1, 160000)
    );
}
