package com.chaseschwartz.extractcraft.items;

import java.util.List;

public record LooseLootDefinition(String id, String displayName, String category, String rarity, int tier, String description, double weight, int gridWidth, int gridHeight, int value) {
    public static final List<LooseLootDefinition> DEFINITIONS = List.of(
            new LooseLootDefinition("sealed_cable_bundle", "Sealed Cable Bundle", "electronics", "blue", 2, "A sealed bundle of military-grade cable used in field repairs.", 0.6D, 1, 1, 420),
            new LooseLootDefinition("field_radio_battery", "Field Radio Battery", "electronics", "blue", 2, "A rugged battery pulled from a field radio pack.", 0.9D, 1, 1, 560),
            new LooseLootDefinition("cracked_rangefinder_lens", "Cracked Rangefinder Lens", "optics", "blue", 2, "A damaged optic lens still useful for calibration parts.", 0.4D, 1, 1, 680),
            new LooseLootDefinition("broken_red_dot_housing", "Broken Red Dot Housing", "optics", "blue", 2, "A cracked sight shell with salvageable mounting hardware.", 0.5D, 1, 1, 520),
            new LooseLootDefinition("tactical_flashlight_core", "Tactical Flashlight Core", "electronics", "blue", 2, "A compact light emitter core from a weapon-mounted flashlight.", 0.5D, 1, 1, 740),
            new LooseLootDefinition("spent_data_tape", "Spent Data Tape", "intel", "blue", 2, "Old magnetic tape with fragments of overwritten patrol logs.", 0.2D, 1, 1, 360),
            new LooseLootDefinition("maintenance_key_fob", "Maintenance Key Fob", "access", "blue", 2, "A worn access fob for maintenance corridors and service doors.", 0.1D, 1, 1, 620),
            new LooseLootDefinition("rusted_dog_tags", "Rusted Dog Tags", "trophy", "blue", 2, "Corroded identification tags from an unknown combatant.", 0.1D, 1, 1, 310),
            new LooseLootDefinition("combat_tourniquet_pack", "Combat Tourniquet Pack", "medical_tech", "blue", 2, "A sealed pack of emergency tourniquets for field trauma.", 0.3D, 1, 1, 480),
            new LooseLootDefinition("sterile_gauze_brick", "Sterile Gauze Brick", "medical_tech", "blue", 2, "Compressed sterile gauze wrapped for rapid medical restock.", 0.4D, 1, 1, 390),
            new LooseLootDefinition("empty_morphine_case", "Empty Morphine Case", "medical_tech", "blue", 2, "An empty injector case with controlled-substance markings.", 0.2D, 1, 1, 330),
            new LooseLootDefinition("antibiotic_strip", "Antibiotic Strip", "medical_tech", "blue", 2, "A sealed strip of antibiotics prized by field medics.", 0.1D, 1, 1, 580),
            new LooseLootDefinition("water_purifier_cartridge", "Water Purifier Cartridge", "survival", "blue", 2, "A filter cartridge for portable purifier systems.", 0.4D, 1, 1, 540),
            new LooseLootDefinition("mre_flavor_pack", "MRE Flavor Pack", "survival", "blue", 2, "A morale-saving packet of ration flavoring and salts.", 0.1D, 1, 1, 260),
            new LooseLootDefinition("compressed_fuel_tab", "Compressed Fuel Tab", "industrial", "blue", 2, "A dense fuel tab for emergency burners and field stoves.", 0.5D, 1, 1, 430),
            new LooseLootDefinition("spark_plug_set", "Spark Plug Set", "industrial", "blue", 2, "A matched set of plugs scavenged from motor pool stock.", 0.5D, 1, 1, 610),
            new LooseLootDefinition("worn_tool_roll", "Worn Tool Roll", "tools", "blue", 2, "A canvas roll containing battered but usable field tools.", 1.0D, 1, 2, 750),
            new LooseLootDefinition("duct_tape_stack", "Duct Tape Stack", "tools", "blue", 2, "Multiple tape rolls flattened for pack storage.", 0.3D, 1, 1, 300),
            new LooseLootDefinition("brass_screw_tin", "Brass Screw Tin", "tools", "blue", 2, "A rattling tin of small brass fasteners.", 0.4D, 1, 1, 290),
            new LooseLootDefinition("electrical_relay", "Electrical Relay", "electronics", "blue", 2, "A boxed relay module used in security and power panels.", 0.3D, 1, 1, 650),
            new LooseLootDefinition("ceramic_fuse", "Ceramic Fuse", "electronics", "blue", 2, "A heat-resistant fuse for older industrial circuits.", 0.2D, 1, 1, 370),
            new LooseLootDefinition("signal_flare_tube", "Signal Flare Tube", "survival", "blue", 2, "A sealed flare tube used to mark extraction or distress points.", 0.6D, 1, 2, 690),
            new LooseLootDefinition("training_ammo_voucher", "Training Ammo Voucher", "intel", "blue", 2, "A stamped voucher redeemable at a restricted training armory.", 0.1D, 1, 1, 450),
            new LooseLootDefinition("laminated_zone_map", "Laminated Zone Map", "intel", "blue", 2, "A weatherproof map marked with old patrol routes.", 0.2D, 1, 1, 820),
            new LooseLootDefinition("bent_weapon_rail", "Bent Weapon Rail", "weapon_parts", "blue", 2, "A damaged rail section that can still be milled for parts.", 0.5D, 1, 1, 430),
            new LooseLootDefinition("cracked_polymer_grip", "Cracked Polymer Grip", "weapon_parts", "blue", 2, "A split grip with intact screws and texture panels.", 0.4D, 1, 1, 360),
            new LooseLootDefinition("oily_cleaning_cloth", "Oily Cleaning Cloth", "tools", "blue", 2, "A treated cloth used for weapon and tool maintenance.", 0.1D, 1, 1, 250),
            new LooseLootDefinition("pocket_multimeter", "Pocket Multimeter", "electronics", "blue", 2, "A compact meter for diagnosing circuits under fire.", 0.4D, 1, 1, 900),
            new LooseLootDefinition("stripped_circuit_board", "Stripped Circuit Board", "electronics", "blue", 2, "A salvage board with a few valuable chips still attached.", 0.2D, 1, 1, 770),
            new LooseLootDefinition("damaged_keypad_panel", "Damaged Keypad Panel", "security", "blue", 2, "A battered keypad panel from a locked facility door.", 0.7D, 1, 2, 880),
            new LooseLootDefinition("cheap_optic_mount", "Cheap Optic Mount", "optics", "blue", 2, "A low-grade optic mount with serviceable clamp hardware.", 0.2D, 1, 1, 340),
            new LooseLootDefinition("field_notebook", "Field Notebook", "intel", "blue", 2, "A pocket notebook filled with partial grid references.", 0.2D, 1, 1, 470),
            new LooseLootDefinition("ration_coupon_stack", "Ration Coupon Stack", "survival", "blue", 2, "A bundle of ration coupons still recognized by some traders.", 0.1D, 1, 1, 280),
            new LooseLootDefinition("plastic_med_vials", "Plastic Med Vials", "medical_tech", "blue", 2, "Clean plastic vials useful for field sample storage.", 0.2D, 1, 1, 520),
            new LooseLootDefinition("hydraulic_valve", "Hydraulic Valve", "industrial", "blue", 2, "A heavy valve from a vehicle or loading system.", 1.1D, 1, 2, 980),
            new LooseLootDefinition("copper_wire_spool", "Copper Wire Spool", "electronics", "blue", 2, "A compact spool of insulated copper wire.", 0.6D, 1, 1, 640),
            new LooseLootDefinition("cracked_phone_screen", "Cracked Phone Screen", "electronics", "blue", 2, "A cracked display panel with recoverable touch layers.", 0.1D, 1, 1, 410),
            new LooseLootDefinition("folded_evacuate_notice", "Folded Evacuation Notice", "intel", "blue", 2, "An evacuation notice with handwritten route changes.", 0.1D, 1, 1, 270),
            new LooseLootDefinition("security_badge_blank", "Security Badge Blank", "access", "blue", 2, "A blank badge ready for encoding or forgery.", 0.1D, 1, 1, 580),
            new LooseLootDefinition("low_grade_lubricant", "Low-Grade Lubricant", "tools", "blue", 2, "A cheap lubricant tube useful for locks and worn machinery.", 0.4D, 1, 1, 390),
            new LooseLootDefinition("encrypted_usb_token", "Encrypted USB Token", "electronics", "purple", 3, "A locked token containing encrypted facility credentials.", 0.1D, 1, 1, 2200),
            new LooseLootDefinition("drone_flight_controller", "Drone Flight Controller", "electronics", "purple", 3, "A compact controller board for small reconnaissance drones.", 0.5D, 1, 1, 3600),
            new LooseLootDefinition("thermal_lens_module", "Thermal Lens Module", "optics", "purple", 3, "A sensitive lens module used in thermal imaging devices.", 0.4D, 1, 1, 5100),
            new LooseLootDefinition("night_vision_tube", "Night Vision Tube", "optics", "purple", 3, "A fragile intensifier tube for night vision assemblies.", 0.3D, 1, 2, 4700),
            new LooseLootDefinition("ballistic_fiber_roll", "Ballistic Fiber Roll", "armor_materials", "purple", 3, "A roll of woven ballistic fiber for armor repair.", 1.1D, 1, 2, 2800),
            new LooseLootDefinition("ceramic_plate_insert", "Ceramic Plate Insert", "armor_materials", "purple", 3, "A dense ceramic insert cut for plate carrier systems.", 2.3D, 2, 2, 4100),
            new LooseLootDefinition("composite_helmet_shell", "Composite Helmet Shell", "armor_materials", "purple", 3, "A shaped helmet shell awaiting liner and hardware.", 1.6D, 2, 2, 3900),
            new LooseLootDefinition("kevlar_stitch_kit", "Kevlar Stitch Kit", "armor_materials", "purple", 3, "A reinforced stitching kit for torn combat textiles.", 0.7D, 1, 1, 2500),
            new LooseLootDefinition("suppressor_baffle_stack", "Suppressor Baffle Stack", "weapon_parts", "purple", 3, "A machined stack of baffles for suppressor rebuilds.", 0.6D, 1, 1, 3300),
            new LooseLootDefinition("precision_trigger_group", "Precision Trigger Group", "weapon_parts", "purple", 3, "A tuned trigger group wrapped in oil paper.", 0.5D, 1, 1, 4200),
            new LooseLootDefinition("carbon_handguard", "Carbon Handguard", "weapon_parts", "purple", 3, "A light carbon handguard for modern rifle builds.", 0.7D, 1, 2, 3100),
            new LooseLootDefinition("smart_magazine_sensor", "Smart Magazine Sensor", "weapon_parts", "purple", 3, "A tiny sensor pack for round-counting magazines.", 0.2D, 1, 1, 2600),
            new LooseLootDefinition("tactical_tablet", "Tactical Tablet", "electronics", "purple", 3, "A hardened tablet with cracked but readable tactical overlays.", 0.8D, 2, 2, 6200),
            new LooseLootDefinition("satellite_phone", "Satellite Phone", "electronics", "purple", 3, "A satellite handset with a restricted network profile.", 0.7D, 1, 2, 5400),
            new LooseLootDefinition("secure_radio_module", "Secure Radio Module", "electronics", "purple", 3, "An encrypted module used in secure squad radios.", 0.6D, 1, 1, 4300),
            new LooseLootDefinition("biometric_scanner", "Biometric Scanner", "security", "purple", 3, "A palm scanner pulled from a checkpoint access post.", 0.5D, 1, 1, 4900),
            new LooseLootDefinition("lab_sample_cooler", "Lab Sample Cooler", "medical_tech", "purple", 3, "An insulated cooler for transporting volatile medical samples.", 1.8D, 2, 2, 5700),
            new LooseLootDefinition("surgical_stapler_kit", "Surgical Stapler Kit", "medical_tech", "purple", 3, "A sealed kit for fast wound closure in the field.", 0.5D, 1, 1, 2400),
            new LooseLootDefinition("hemostatic_injector_pack", "Hemostatic Injector Pack", "medical_tech", "purple", 3, "A pack of injector cartridges for severe bleeding control.", 0.4D, 1, 1, 3200),
            new LooseLootDefinition("prototype_splint_brace", "Prototype Splint Brace", "medical_tech", "purple", 3, "A collapsible brace used by combat trauma teams.", 0.9D, 1, 2, 2700),
            new LooseLootDefinition("blacksite_access_badge", "Blacksite Access Badge", "access", "purple", 3, "A restricted badge tied to blacksite facility access.", 0.1D, 1, 1, 6500),
            new LooseLootDefinition("armory_maintenance_card", "Armory Maintenance Card", "access", "purple", 3, "A maintenance card for secured armory service panels.", 0.1D, 1, 1, 3700),
            new LooseLootDefinition("redacted_patrol_orders", "Redacted Patrol Orders", "intel", "purple", 3, "Orders with heavy redactions and a few useful route timings.", 0.1D, 1, 1, 4500),
            new LooseLootDefinition("sealed_evidence_pouch", "Sealed Evidence Pouch", "intel", "purple", 3, "A tamper-marked pouch containing chain-of-custody fragments.", 0.2D, 1, 1, 2900),
            new LooseLootDefinition("military_crypto_ledger", "Military Crypto Ledger", "intel", "purple", 3, "A paper ledger of rotating military crypto references.", 0.3D, 1, 1, 7100),
            new LooseLootDefinition("hardened_drive_caddy", "Hardened Drive Caddy", "electronics", "purple", 3, "A shockproof drive carrier from a command workstation.", 0.6D, 1, 1, 3900),
            new LooseLootDefinition("optic_calibration_tool", "Optic Calibration Tool", "optics", "purple", 3, "A precise tool for aligning advanced sight modules.", 0.4D, 1, 1, 2300),
            new LooseLootDefinition("compact_signal_jammer", "Compact Signal Jammer", "security", "purple", 3, "A compact jammer used to blind short-range sensors.", 0.9D, 1, 2, 6900),
            new LooseLootDefinition("reinforced_cable_harness", "Reinforced Cable Harness", "industrial", "purple", 3, "A rugged harness from a military generator bay.", 1.4D, 1, 2, 2600),
            new LooseLootDefinition("restricted_medical_manifest", "Restricted Medical Manifest", "intel", "purple", 3, "A manifest listing controlled medical shipments and routing.", 0.1D, 1, 1, 5200),
            new LooseLootDefinition("quantum_signal_chip", "Quantum Signal Chip", "electronics", "gold", 4, "A rare signal chip built for hardened encrypted relays.", 0.1D, 1, 1, 14500),
            new LooseLootDefinition("classified_ssd_array", "Classified SSD Array", "electronics", "gold", 4, "A compact SSD array marked for classified systems only.", 0.5D, 1, 1, 18200),
            new LooseLootDefinition("prototype_drone_brain", "Prototype Drone Brain", "electronics", "gold", 4, "A prototype processor cluster from an autonomous drone.", 0.8D, 2, 2, 24000),
            new LooseLootDefinition("thermal_imaging_core", "Thermal Imaging Core", "optics", "gold", 4, "The core sensor package from a military thermal optic.", 0.6D, 1, 2, 21000),
            new LooseLootDefinition("advanced_nvg_assembly", "Advanced NVG Assembly", "optics", "gold", 4, "A complete night vision assembly with intact tubes.", 0.8D, 2, 2, 17500),
            new LooseLootDefinition("smart_ballistic_plate", "Smart Ballistic Plate", "armor_materials", "gold", 4, "A smart plate with embedded impact telemetry layers.", 3.0D, 2, 2, 19500),
            new LooseLootDefinition("reactive_armor_tile", "Reactive Armor Tile", "armor_materials", "gold", 4, "A sealed reactive tile from an experimental armor kit.", 3.6D, 2, 2, 22500),
            new LooseLootDefinition("exo_fiber_harness", "Exo-Fiber Harness", "armor_materials", "gold", 4, "A woven harness designed to anchor powered exo components.", 2.2D, 2, 3, 27800),
            new LooseLootDefinition("precision_gyro_stabilizer", "Precision Gyro Stabilizer", "weapon_parts", "gold", 4, "A stabilizer module used in precision weapon platforms.", 0.7D, 1, 1, 12800),
            new LooseLootDefinition("match_grade_bolt_carrier", "Match-Grade Bolt Carrier", "weapon_parts", "gold", 4, "A match-grade carrier machined to tight tolerances.", 0.8D, 1, 1, 9800),
            new LooseLootDefinition("adaptive_suppressor_core", "Adaptive Suppressor Core", "weapon_parts", "gold", 4, "A suppressor core with adjustable gas-flow chambers.", 0.8D, 1, 2, 15600),
            new LooseLootDefinition("prototype_ammo_feed_unit", "Prototype Ammo Feed Unit", "weapon_parts", "gold", 4, "A prototype feed unit for high-rate ammunition systems.", 1.4D, 2, 2, 18400),
            new LooseLootDefinition("secure_ops_laptop", "Secure Ops Laptop", "electronics", "gold", 4, "A hardened operations laptop with secure boot hardware.", 2.4D, 2, 2, 33500),
            new LooseLootDefinition("commanders_encrypted_drive", "Commander's Encrypted Drive", "intel", "gold", 4, "A restricted drive containing encrypted command data.", 0.2D, 1, 1, 26000),
            new LooseLootDefinition("black_budget_payroll", "Black Budget Payroll", "intel", "gold", 4, "A payroll ledger tied to off-books battlefield contractors.", 0.2D, 1, 1, 31000),
            new LooseLootDefinition("diplomatic_courier_pouch", "Diplomatic Courier Pouch", "contraband", "gold", 4, "A sealed courier pouch with diplomatic chain markings.", 0.7D, 1, 2, 29500),
            new LooseLootDefinition("lab_grade_stimulant_case", "Lab-Grade Stimulant Case", "medical_tech", "gold", 4, "A locked case of high-grade stimulant compounds.", 1.2D, 2, 2, 16800),
            new LooseLootDefinition("portable_blood_analyzer", "Portable Blood Analyzer", "medical_tech", "gold", 4, "A portable analyzer used by trauma teams and field labs.", 0.9D, 1, 2, 11200),
            new LooseLootDefinition("military_antidote_injector", "Military Antidote Injector", "medical_tech", "gold", 4, "A restricted injector for battlefield toxin exposure.", 0.3D, 1, 1, 13400),
            new LooseLootDefinition("nano_suture_cartridge", "Nano-Suture Cartridge", "medical_tech", "gold", 4, "A tiny cartridge of experimental wound-closure filament.", 0.2D, 1, 1, 8900),
            new LooseLootDefinition("heart_of_the_dam", "Heart of the Dam", "trophy", "red", 5, "A legendary industrial core pulled from the dam control complex.", 4.5D, 3, 3, 85000),
            new LooseLootDefinition("blacksite_master_ledger", "Blacksite Master Ledger", "intel", "red", 5, "A master ledger linking blacksite operations, accounts, and handlers.", 0.7D, 2, 2, 76000),
            new LooseLootDefinition("prototype_exo_core", "Prototype Exo-Core", "armor_materials", "red", 5, "A rare powered exo core with intact control architecture.", 5.0D, 2, 3, 112000),
            new LooseLootDefinition("quantum_encryption_vault", "Quantum Encryption Vault", "electronics", "red", 5, "A hardened quantum vault containing unbroken encryption hardware.", 2.8D, 2, 2, 135000),
            new LooseLootDefinition("gold_tactical_pack_frame", "Gold Tactical Pack Frame", "armor_materials", "red", 5, "A gold-anodized frame from an elite tactical pack prototype.", 3.4D, 2, 3, 54000),
            new LooseLootDefinition("gold_ballistic_helmet_core", "Gold Ballistic Helmet Core", "armor_materials", "red", 5, "A rare helmet core with dense premium ballistic layers.", 2.6D, 2, 2, 62000),
            new LooseLootDefinition("command_ai_processor", "Command AI Processor", "electronics", "red", 5, "A rare command processor pulled from a hardened battlefield AI unit.", 1.3D, 2, 2, 148000),
            new LooseLootDefinition("satellite_uplink_beacon", "Satellite Uplink Beacon", "security", "red", 5, "A military uplink beacon capable of reaching restricted satellites.", 2.1D, 2, 2, 91000),
            new LooseLootDefinition("classified_warhead_circuit", "Classified Warhead Circuit", "contraband", "red", 5, "A classified firing circuit from a banned warhead program.", 0.9D, 1, 2, 125000),
            new LooseLootDefinition("omega_protocol_drive", "Omega Protocol Drive", "intel", "red", 5, "A restricted drive carrying fragments of Omega Protocol orders.", 0.2D, 1, 1, 160000)
    );
}
